### ISSUE TITLE
Add reorder option for Galleries to controller 

### ISSUE THREAD

**Issue by Hessel91** [Rebel59/oc-isogallery-plugin#4] opened 2020-01-18 16:59 UTC
Hi, 

I try to add the reorder option to the controller for Galleries, however when I press the reorder button I get error 500 message. 
Can you perhaps tell me what I'm doing wrong?

-I added column mysort_order to the rebel59_isogallery_galleries database.
-In the list controller behavior I added mysort_order to the sorting column.
-I created a reorder controller sorting "title"

My code:

rebel59/isogallery/controllers/galleries/config_reorder.yaml 
`title: galleries
modelClass: Rebel59\Isogallery\Models\Gallery
nameFrom: title
toolbar:
    buttons: reorder_toolbar
`

rebel59/isogallery/controllers/galleries/_reorder_toolbar.htm

```
<div data-control="toolbar">
    <a href="<?= Backend::url('rebel59/isogallery/galleries') ?>" class="btn btn-primary oc-icon-caret-left"><?= e(trans('backend::lang.form.return_to_list')) ?></a>
</div>
```

rebel59/isogallery/controllers/galleries/reorder.htm
```
<?php Block::put('breadcrumb') ?>
    <ul>
        <li><a href="<?= Backend::url('rebel59/isogallery/galleries') ?>">galleries</a></li>
        <li><?= e($this->pageTitle) ?></li>
    </ul>
<?php Block::endPut() ?>

<?= $this->reorderRender() ?>
```

rebel59/isogallery/controllers/galleries/_list_toolbar.htm
```
<div data-control="toolbar">
    <a
        href="<?= Backend::url('rebel59/isogallery/galleries/create') ?>"
        class="btn btn-primary oc-icon-plus">
        Nieuw Item
    </a>
    <a href="<?= Backend::url('rebel59/isogallery/galleries/reorder') ?>" class="btn btn-default oc-icon-list"><?= e(trans('backend::lang.reorder.default_title')) ?></a>
</div>
```

rebel59/isogallery/controllers/Galleries.php
```
<?php namespace Rebel59\Isogallery\Controllers;

use BackendMenu;
use Backend\Classes\Controller;

/**
 * Galleries Back-end Controller
 */
class Galleries extends Controller
{
    public $implement = [
        'Backend.Behaviors.FormController',
        'Backend.Behaviors.ListController',
        'Backend\Behaviors\ReorderController',
        'Backend.Behaviors.RelationController'
    ];

    public $formConfig = 'config_form.yaml';
    public $listConfig = 'config_list.yaml';
    public $relationConfig = 'config_relation.yaml';
    public $reorderConfig = 'config_reorder.yaml';

    public function __construct()
    {
        parent::__construct();

        BackendMenu::setContext('Rebel59.Isogallery', 'isogallery', 'galleries');
    }
}
```

**Comment by CptMeatball** [comment] 2020-01-20 08:24
Can you post the 500 message and a Gist / Repo of your actual code?

At first glance it looks like you're missing the sortable trait in the `Gallery` Model.

**Comment by Hessel91** [comment] 2020-01-20 21:36
You are right, it was indeed the sortable trait. After that I got this error when trying to sort   
![image](https://user-images.githubusercontent.com/7326568/72758920-70374f80-3bd4-11ea-93db-7bf592d77b24.png)

I tried to change timestamp to datetime format but that wasn't working. Do you have any idea?

**Comment by CptMeatball** [comment] 2020-01-21 10:45
Not sure what's going wrong there, but seems like a faulty migration. 

Anyway, see this branch for a working solution. 

https://github.com/Rebel59/oc-isogallery-plugin/tree/galleries-reorder

**Comment by CptMeatball** [comment] 2020-01-23 16:08
Closing this as it seems like the problem is solved. Please comment if this is still important for you.

**Closed as completed by CptMeatball** 2020-01-23 16:08 UTC
